
export const famousStates = [
    "New York",
    "Île-de-France",
    "England",
    "Tokyo",
    "Lazio",
    "New South Wales",
    "Catalonia",
    "Dubai",
    "California",
    "Rio de Janeiro",
    "Berlin",
    "Moscow",
    "Ontario",
    "Singapore",
    "Istanbul",
    "Western Cape",
    "Bangkok",
    "North Holland",
    "Mexico City",
    "Hong Kong",
    "Tuscany",
    "Veneto",
    "Attica",
    "Prague",
    "Vienna",
    "Seoul",
    "Maharashtra",
    "Buenos Aires",
    "Lisbon",
    "Stockholm",
    "Zurich",
    "Dublin",
    "Scotland",
    "Copenhagen",
    "Helsinki",
    "Oslo",
    "Auckland",
    "British Columbia",
    "Madrid",
    "Lombardy",
    "Brussels",
    "Warsaw",
    "Budapest",
    "Luxembourg",
    "Dubrovnik",
    "Reykjavik",
    "Lesser Poland",
    "Ljubljana",
    "Malta",
    "Cyclades",
    "Balearic Islands",
    "Provence-Alpes-Côte d'Azur",
    "São Paulo",
    "Bogotá",
    "Illinois",
    "Florida",
    "Louisiana",
    "Washington",
    "Colorado",
    "Nevada",
    "District of Columbia",
    "Pennsylvania",
    "Massachusetts",
    "Georgia",
    "Texas",
    "Arizona",
    "Hawaii",
    "Alaska",
    "Oregon",
    "Alberta",
    "Quebec",
    "Manitoba",
    "Saskatchewan",
    "Nova Scotia",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Yukon",
    "Nunavut",
    "Delhi",
    "West Bengal",
    "Tamil Nadu",
    "Karnataka",
    "Telangana",
    "Rajasthan",
    "Gujarat",
    "Uttar Pradesh",
    "Madhya Pradesh",
    "Bihar",
    "Andhra Pradesh",
    "Kerala",
    "Punjab",
    "Haryana",
    "Odisha",
    "Jharkhand",
    "Uttarakhand",
    "Chhattisgarh",
    "Assam",
    "Himachal Pradesh",
    "Chandigarh",
    "Jammu and Kashmir",
    "Goa",
    "Puducherry",
    "Tripura",
    "Meghalaya",
    "Manipur",
    "Nagaland",
    "Arunachal Pradesh",
    "Mizoram",
    "Sikkim",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Andaman and Nicobar Islands",
    "Ladakh",
    "Lakshadweep",
  ];
  export const famousCities = [
  // Worldwide Famous Cities
  "New York City",
  "Paris",
  "London",
  "Tokyo",
  "Rome",
  "Sydney",
  "Barcelona",
  "Dubai",
  "Los Angeles",
  "Rio de Janeiro",
  "Berlin",
  "Moscow",
  "Toronto",
  "Singapore",
  "Istanbul",
  "Cape Town",
  "Bangkok",
  "Amsterdam",
  "Mexico City",
  "Hong Kong",
  "San Francisco",
  "Florence",
  "Venice",
  "Athens",
  "Prague",
  "Vienna",
  "Seoul",
  "Mumbai",
  "Buenos Aires",
  "Lisbon",
  "Stockholm",
  "Zurich",
  "Dublin",
  "Edinburgh",
  "Copenhagen",
  "Helsinki",
  "Oslo",
  "Auckland",
  "Vancouver",
  "Madrid",
  "Milan",
  "Brussels",
  "Warsaw",
  "Budapest",
  "Luxembourg City",
  "Dubrovnik",
  "Reykjavik",
  "Krakow",
  "Ljubljana",
  "Valletta",
  "Santorini",
  "Ibiza",
  "Cannes",
  "Nice",
  "Monaco",
  "Monte Carlo",
  "São Paulo",
  "Bogotá",
  "Chicago",
  "Miami",
  "San Diego",
  "Orlando",
  "New Orleans",
  "Seattle",
  "Denver",
  "Las Vegas",
  "Washington, D.C.",
  "Philadelphia",
  "Boston",
  "Atlanta",
  "Houston",
  "Dallas",
  "Phoenix",
  "Honolulu",
  "Anchorage",
  "Portland",
  "Calgary",
  "Montreal",
  "Quebec City",
  "Ottawa",
  "Winnipeg",
  "Saskatoon",
  "Regina",
  "Edmonton",
  "Halifax",
  "St. John's",
  "Yellowknife",
  "Whitehorse",
  "Iqaluit",
  "Thunder Bay",
  "Sudbury",
  "Windsor",
  "Sarnia",
  "London",
  "Hamilton",
  "Niagara Falls",
  "Buffalo",
  "Detroit",
  "Cleveland",
  "Rochester",
  "Syracuse",
  "Pittsburgh",
  "Providence",
  "Victoria",
  "San Jose",
  "Albuquerque",
  "Salt Lake City",
  "Boise",
  "Billings",
  "Sacramento",
  "Fresno",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Jaipur",
  "Ahmedabad",
  "Surat",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Visakhapatnam",
  "Indore",
  "Thane",
  "Bhopal",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Ranchi",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Allahabad",
  "Ranchi",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Thiruvananthapuram",
  "Solapur",
  "Tiruchirappalli",
  "Bareilly",
  "Moradabad",
  "Mysore",
  "Tiruppur",
  "Gurgaon",
  "Aligarh",
  "Jalandhar",
  "Bhubaneswar",
  "Salem",
  "Warangal",
  "Guntur",
  "Bhiwandi",
  "Saharanpur",
  "Gorakhpur",
  "Bikaner",
  "Amravati",
  "Noida",
  "Jamshedpur",
  "Bhilai",
  "Cuttack",
  "Kochi",
  "Udaipur",
  "Dehradun",
  "Asansol",
  "Nanded",
  "Ajmer",
  "Jamnagar",
  "Ujjain",
  "Jhansi",
  "Pondicherry",
  "Nellore",
  "Jammu",
  "Belgaum",
  "Gulbarga",
  "Gaya",
  "Jalgaon",
  "Malegaon",
  "Akola",
  "Dhule",
  "Ahmednagar",
  "Ambernath",
  "Bhind",
  "Ulhasnagar",
  "Ichalkaranji",
  "Tirupati",
  "Hosur",
  "Nizamabad",
  "Adoni",
  "Karnal",
  "Bihar Sharif",
  "Panipat",
  "Darbhanga",
  "Bally",
  "Aizawl",
  "Dewas",
  "Satna",
  "Mathura",
  "Kollam",
  "Kumbakonam",
  "Mangalore",
  "Alappuzha",
  "Jhunjhunu",
  "Imphal",
  "Silchar",
  "Ambala",
  "Beawar",
  "Sonipat",
  "Pali",
  "Bhagalpur",
  "Agartala",
  "Rourkela",
  "Kottayam",
  "Bhimavaram",
  "Latur",
  "Karimnagar",
  "Bhusawal",
  "Kumbakonam",
  "Ongole",
  "Nandyal",
  "Morena",
  "Bhiwani",
  "Anantapur",
  "Raichur",
  "Haridwar",
  "Singrauli",
  "Yamunanagar",
  "Navi Mumbai",
];
